import { NextResponse } from 'next/server';
import { callTool, isConfigured, resetSession } from '@/lib/gateway-client';
import { ROVO_SERVER_NAME } from '../_shared';
import { rateLimit } from '../_rateLimit';

function rovo(toolName: string): string {
  return `${ROVO_SERVER_NAME}__${toolName}`;
}

function extractText(result: { content: Array<{ type: string; text?: string }> }): string {
  const block = result.content.find((c) => c.type === 'text');
  return block?.text ?? '';
}

export interface CreateDocResponse {
  success: boolean;
  pageUrl?: string;
  pageTitle?: string;
  policyBlocked?: boolean;
  blockReason?: string;
  source: 'gateway' | 'mock';
}

async function createViaGateway(title: string, content: string): Promise<CreateDocResponse> {
  // Step 1: Get cloudId
  const resourcesResult = await callTool(rovo('getAccessibleAtlassianResources'), {});
  if (resourcesResult.isError) throw new Error(`Tool error: ${extractText(resourcesResult)}`);
  const resources = JSON.parse(extractText(resourcesResult));
  const cloudId: string = Array.isArray(resources) ? resources[0]?.id : resources?.id;
  if (!cloudId) throw new Error('No Atlassian cloud resources found');

  // Step 2: Get first available space
  const spacesResult = await callTool(rovo('getConfluenceSpaces'), { cloudId, limit: 1 });
  if (spacesResult.isError) {
    const errText = extractText(spacesResult);
    // Check for policy block
    if (errText.toLowerCase().includes('policy') || errText.toLowerCase().includes('denied') || errText.toLowerCase().includes('blocked')) {
      return {
        success: false,
        policyBlocked: true,
        blockReason: errText,
        source: 'gateway',
      };
    }
    throw new Error(`Tool error: ${errText}`);
  }
  const spacesText = extractText(spacesResult);
  const spacesData = JSON.parse(spacesText);
  const spaces = spacesData?.results ?? spacesData ?? [];
  const spaceId = Array.isArray(spaces) && spaces.length > 0 ? (spaces[0].id as string) : null;
  if (!spaceId) throw new Error('No Confluence spaces found');

  // Step 3: Create page
  const createResult = await callTool(rovo('createConfluencePage'), {
    cloudId,
    spaceId,
    title,
    body: content,
    contentFormat: 'markdown',
  });

  if (createResult.isError) {
    const errText = extractText(createResult);
    // Check for policy block or approval required
    if (errText.toLowerCase().includes('policy') || errText.toLowerCase().includes('denied') || errText.toLowerCase().includes('blocked')) {
      return {
        success: false,
        policyBlocked: true,
        blockReason: errText,
        source: 'gateway',
      };
    }
    if (errText.toLowerCase().includes('approval') || errText.toLowerCase().includes('pending')) {
      return {
        success: false,
        policyBlocked: true,
        blockReason: 'Write operation requires approval from an admin before execution.',
        source: 'gateway',
      };
    }
    throw new Error(`Tool error: ${errText}`);
  }

  const pageText = extractText(createResult);
  const pageData = JSON.parse(pageText);
  const pageUrl = (pageData?._links?.webui as string) ?? (pageData?.url as string) ?? '';

  return {
    success: true,
    pageUrl,
    pageTitle: title,
    source: 'gateway',
  };
}

export async function POST(request: Request) {
  const rateLimited = rateLimit(request);
  if (rateLimited) return rateLimited;

  try {
    const body = await request.json();
    const title = (body.title as string) ?? 'Architecture Recommendation';
    const content = (body.content as string) ?? '# Architecture Document\n\nGenerated by MCP demo.';

    let response: CreateDocResponse;

    if (isConfigured()) {
      try {
        response = await createViaGateway(title, content);
      } catch (err) {
        console.warn('[create-confluence-doc] Gateway failed, using mock:', err instanceof Error ? err.message : err);
        resetSession();
        response = {
          success: true,
          pageUrl: `https://your-domain.atlassian.net/wiki/spaces/ARCH/pages/mock-${Date.now()}`,
          pageTitle: title,
          source: 'mock',
        };
      }
    } else {
      response = {
        success: true,
        pageUrl: `https://your-domain.atlassian.net/wiki/spaces/ARCH/pages/mock-${Date.now()}`,
        pageTitle: title,
        source: 'mock',
      };
    }

    return NextResponse.json(response);
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
