import { NextResponse } from 'next/server';
import { callTool, isConfigured } from '@/lib/gateway-client';
import { ROVO_SERVER_NAME, AgentActionsInputSchema } from '../_shared';
import { rateLimit } from '../_rateLimit';

interface ActionResult {
  type: string;
  description: string;
  toolUsed: string;
  success: boolean;
  policyBlocked?: boolean;
  approvalRequired?: boolean;
  blockReason?: string;
  details?: Record<string, unknown>;
}

function rovo(toolName: string): string {
  return `${ROVO_SERVER_NAME}__${toolName}`;
}

function extractText(result: { content: Array<{ type: string; text?: string }> }): string {
  const block = result.content.find((c) => c.type === 'text');
  return block?.text ?? '';
}

export async function POST(request: Request) {
  const rateLimited = rateLimit(request);
  if (rateLimited) return rateLimited;

  try {
    const body = await request.json();
    const parsed = AgentActionsInputSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: 'Invalid input', details: parsed.error.issues }, { status: 400 });
    }
    const {
      projectKey,
      enabledActions,
      issueKey,
      architectureTitle,
      architectureContent,
      jiraTickets,
    } = parsed.data;

    const actions: ActionResult[] = [];

    if (!isConfigured()) {
      // Mock mode — simulate all enabled actions
      return NextResponse.json({
        actions: getMockActions(enabledActions, projectKey, issueKey),
      });
    }

    // Get cloudId
    let cloudId: string;
    try {
      const resourcesResult = await callTool(rovo('getAccessibleAtlassianResources'), {});
      if (resourcesResult.isError) throw new Error(extractText(resourcesResult));
      const resourcesText = extractText(resourcesResult);
      const resources = JSON.parse(resourcesText);
      cloudId = Array.isArray(resources) ? resources[0]?.id : resources?.id;
      if (!cloudId) throw new Error('No Atlassian cloud resources found');
    } catch (err) {
      console.warn('[agent-actions] Cannot get cloudId, using mock:', err instanceof Error ? err.message : err);
      return NextResponse.json({
        actions: getMockActions(enabledActions, projectKey, issueKey),
      });
    }

    // Execute each enabled action
    for (const action of enabledActions) {
      try {
        if (action === 'label_issues' && issueKey) {
          const result = await callTool(rovo('editJiraIssue'), {
            cloudId,
            issueIdOrKey: issueKey,
            fields: {
              labels: { add: ['ai-deployment', 'compliance-review'] },
            },
          });

          if (result.isError) {
            const errText = extractText(result);
            actions.push({
              type: 'label_issues',
              description: `Add labels to ${issueKey}`,
              toolUsed: 'editJiraIssue',
              success: false,
              ...detectPolicyBlock(errText),
            });
          } else {
            actions.push({
              type: 'label_issues',
              description: `Added "ai-deployment", "compliance-review" labels to ${issueKey}`,
              toolUsed: 'editJiraIssue',
              success: true,
              details: { issueKey, labels: ['ai-deployment', 'compliance-review'] },
            });
          }
        }

        if (action === 'add_comment' && issueKey) {
          const commentBody = `**AI Deployment Analysis Summary**\n\nThis issue has been reviewed as part of the automated deployment readiness assessment. Key findings:\n- Architecture pattern recommended\n- Compliance requirements identified\n- Implementation plan generated\n\n_Generated by Partner Enablement MCP Demo_`;

          const result = await callTool(rovo('addCommentToJiraIssue'), {
            cloudId,
            issueIdOrKey: issueKey,
            commentBody,
          });

          if (result.isError) {
            const errText = extractText(result);
            actions.push({
              type: 'add_comment',
              description: `Add analysis comment to ${issueKey}`,
              toolUsed: 'addCommentToJiraIssue',
              success: false,
              ...detectPolicyBlock(errText),
            });
          } else {
            actions.push({
              type: 'add_comment',
              description: `Added AI deployment analysis summary comment to ${issueKey}`,
              toolUsed: 'addCommentToJiraIssue',
              success: true,
              details: { issueKey },
            });
          }
        }

        if (action === 'transition_issue' && issueKey) {
          // First get available transitions
          let transitioned = false;
          try {
            const transResult = await callTool(rovo('getTransitionsForJiraIssue'), {
              cloudId,
              issueIdOrKey: issueKey,
            });

            if (!transResult.isError) {
              const transText = extractText(transResult);
              const transData = JSON.parse(transText);
              const transitions = transData?.transitions ?? [];
              // Find "In Progress" transition
              const inProgressTrans = transitions.find(
                (t: Record<string, unknown>) =>
                  ((t.name as string) ?? '').toLowerCase().includes('progress')
              );

              if (inProgressTrans) {
                const doTransResult = await callTool(rovo('transitionJiraIssue'), {
                  cloudId,
                  issueIdOrKey: issueKey,
                  transition: { id: String(inProgressTrans.id) },
                });

                if (doTransResult.isError) {
                  const errText = extractText(doTransResult);
                  actions.push({
                    type: 'transition_issue',
                    description: `Transition ${issueKey} to In Progress`,
                    toolUsed: 'transitionJiraIssue',
                    success: false,
                    ...detectPolicyBlock(errText),
                  });
                } else {
                  actions.push({
                    type: 'transition_issue',
                    description: `Transitioned ${issueKey} to "In Progress"`,
                    toolUsed: 'transitionJiraIssue',
                    success: true,
                    details: { issueKey, newStatus: 'In Progress' },
                  });
                }
                transitioned = true;
              }
            }
          } catch {
            // Fall through to default message
          }

          if (!transitioned) {
            actions.push({
              type: 'transition_issue',
              description: `No "In Progress" transition available for ${issueKey}`,
              toolUsed: 'transitionJiraIssue',
              success: false,
              blockReason: 'No available transition to In Progress status',
            });
          }
        }

        if (action === 'create_confluence' && architectureTitle && architectureContent) {
          // Get spaces first
          let spaceId: string | undefined;
          try {
            const spacesResult = await callTool(rovo('getConfluenceSpaces'), { cloudId });
            if (!spacesResult.isError) {
              const spacesText = extractText(spacesResult);
              const spacesData = JSON.parse(spacesText);
              const spaces = spacesData?.results ?? spacesData ?? [];
              if (Array.isArray(spaces) && spaces.length > 0) {
                spaceId = String(spaces[0].id);
              }
            }
          } catch {
            // No space found
          }

          if (!spaceId) {
            actions.push({
              type: 'create_confluence',
              description: 'Create architecture doc in Confluence',
              toolUsed: 'createConfluencePage',
              success: false,
              blockReason: 'No Confluence space found',
            });
          } else {
            const result = await callTool(rovo('createConfluencePage'), {
              cloudId,
              spaceId,
              title: architectureTitle,
              body: architectureContent,
              contentFormat: 'markdown',
            });

            if (result.isError) {
              const errText = extractText(result);
              actions.push({
                type: 'create_confluence',
                description: 'Create architecture doc in Confluence',
                toolUsed: 'createConfluencePage',
                success: false,
                ...detectPolicyBlock(errText),
              });
            } else {
              const resultText = extractText(result);
              let pageUrl: string | undefined;
              try {
                const resultData = JSON.parse(resultText);
                pageUrl = resultData?._links?.webui
                  ? `${resultData?._links?.base ?? ''}${resultData._links.webui}`
                  : undefined;
              } catch { /* ignore */ }

              actions.push({
                type: 'create_confluence',
                description: `Created "${architectureTitle}" in Confluence`,
                toolUsed: 'createConfluencePage',
                success: true,
                details: { pageTitle: architectureTitle, pageUrl },
              });
            }
          }
        }

        if (action === 'create_jira' && jiraTickets && jiraTickets.length > 0) {
          const createdIssues: Array<{ key: string; summary: string }> = [];
          let blocked = false;
          let blockMsg = '';

          for (const ticket of jiraTickets.slice(0, 5)) {
            const result = await callTool(rovo('createJiraIssue'), {
              cloudId,
              projectKey,
              issueTypeName: ticket.type === 'epic' ? 'Epic' : ticket.type === 'story' ? 'Story' : 'Task',
              summary: ticket.summary,
              description: ticket.description,
            });

            if (result.isError) {
              const errText = extractText(result);
              const detection = detectPolicyBlock(errText);
              if (detection.policyBlocked || detection.approvalRequired) {
                blocked = true;
                blockMsg = detection.blockReason ?? errText;
                break;
              }
            } else {
              const resultText = extractText(result);
              try {
                const issueData = JSON.parse(resultText);
                createdIssues.push({
                  key: issueData.key ?? `${projectKey}-???`,
                  summary: ticket.summary,
                });
              } catch {
                createdIssues.push({ key: `${projectKey}-???`, summary: ticket.summary });
              }
            }
          }

          if (blocked) {
            actions.push({
              type: 'create_jira',
              description: 'Create implementation Jira tickets',
              toolUsed: 'createJiraIssue',
              success: false,
              policyBlocked: true,
              blockReason: blockMsg,
            });
          } else {
            actions.push({
              type: 'create_jira',
              description: `Created ${createdIssues.length} Jira tickets`,
              toolUsed: 'createJiraIssue',
              success: true,
              details: { issues: createdIssues },
            });
          }
        }
      } catch (err) {
        console.warn(`[agent-actions] Action ${action} failed:`, err instanceof Error ? err.message : err);
        actions.push({
          type: action,
          description: `Action failed: ${action}`,
          toolUsed: 'unknown',
          success: false,
          blockReason: err instanceof Error ? err.message : 'Unknown error',
        });
      }
    }

    return NextResponse.json({ actions });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

function detectPolicyBlock(errorText: string): {
  policyBlocked?: boolean;
  approvalRequired?: boolean;
  blockReason?: string;
} {
  const lower = errorText.toLowerCase();
  if (lower.includes('policy') && (lower.includes('blocked') || lower.includes('denied'))) {
    return { policyBlocked: true, blockReason: errorText };
  }
  if (lower.includes('approval') && lower.includes('required')) {
    return { approvalRequired: true, blockReason: errorText };
  }
  return { blockReason: errorText };
}

function getMockActions(enabledActions: string[], projectKey: string, issueKey?: string): ActionResult[] {
  const actions: ActionResult[] = [];
  const key = issueKey ?? `${projectKey}-1`;

  if (enabledActions.includes('label_issues')) {
    actions.push({
      type: 'label_issues',
      description: `Added "ai-deployment", "compliance-review" labels to ${key}`,
      toolUsed: 'editJiraIssue',
      success: true,
      details: { issueKey: key, labels: ['ai-deployment', 'compliance-review'] },
    });
  }
  if (enabledActions.includes('add_comment')) {
    actions.push({
      type: 'add_comment',
      description: `Added AI deployment analysis summary comment to ${key}`,
      toolUsed: 'addCommentToJiraIssue',
      success: true,
      details: { issueKey: key },
    });
  }
  if (enabledActions.includes('transition_issue')) {
    actions.push({
      type: 'transition_issue',
      description: `Transitioned ${key} to "In Progress"`,
      toolUsed: 'transitionJiraIssue',
      success: true,
      details: { issueKey: key, newStatus: 'In Progress' },
    });
  }
  if (enabledActions.includes('create_confluence')) {
    actions.push({
      type: 'create_confluence',
      description: 'Created architecture doc in Confluence',
      toolUsed: 'createConfluencePage',
      success: false,
      policyBlocked: true,
      blockReason: 'Policy "Confluence View-Only" blocks createConfluencePage for this tenant. Write operations require admin approval.',
    });
  }
  if (enabledActions.includes('create_jira')) {
    actions.push({
      type: 'create_jira',
      description: 'Create implementation Jira tickets',
      toolUsed: 'createJiraIssue',
      success: false,
      approvalRequired: true,
      blockReason: 'Policy "Approval for Writes" requires human-in-the-loop approval for createJiraIssue. Approval request submitted.',
    });
  }

  return actions;
}
